spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_data?useSSL=false
    username: root
    password: root

  #JPA Settings
  jpa:
    hibernate:
      ddl-auto: update

resilience4j.ratelimiter:
  instances:
    RateLimiter:
      limitForPeriod: 5
      limitRefreshPeriod: 180s
      timeoutDuration: 0
      registerHealthIndicator: true
      eventConsumerBufferSize: 100
    CommentRateLimiter:
      limitForPeriod: 5
      limitRefreshPeriod: 180s
      timeoutDuration: 0
      registerHealthIndicator: true
      eventConsumerBufferSize: 100

